fix: avoid references that break nixpkgs impurity check on macos (#904)
The testdata were refering to a valid package that's included by default
on macOS, 7h6icyvqv6lqd0bcx41c8h3615rjcqb2-libiconv-109.100.2, and due
to its strict reference check, it was failing to build:

```
error: fixed-output derivations must not reference store paths: '/nix/store/q3wivx2l94r75dz4nc5b0403cl0iy7jb-source.drv' references 1 distinct paths, e.g. '/nix/store/7h6icyvqv6lqd0bcx41c8h3615rjcqb2-libiconv-109.100.2'
error: Cannot build '/nix/store/43hydg0l64d0xszpgj2sknf8yxcl8spd-ncps-0.8.5.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/c9di78n2bwh5j7z0lqvshwjmcwsdgan7-ncps-0.8.5
```

Assemble the reference with string concatination to fool the reference
check.

(cherry picked from commit 3455feae5d042f36ddf36ad3b121542806875f31)